
#ifndef _SENSOR_CM_CONVERTER_H
#define _SENSOR_CM_CONVERTER_H

int8_t S1_convert_sensor_value_left_front(int8_t digital_distance);
int8_t S2_convert_sensor_value__left_back(int8_t digital_distance);
int8_t S3_convert_sensor_value_right_front(int8_t digital_distance);
int8_t S4_convert_sensor_value_right_back(int8_t digital_distance);
int8_t S5_convert_sensor_value_front_long(int8_t digital_distance);


#endif